### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [calvinwilliams/hetao#3]
I guess that a different program design will be needed for your function "[sig_set_flag](https://github.com/calvinwilliams/hetao/blob/029690fe2638a7568483ea3c9f768dd1c1b7b845/src/MonitorProcess.c#L18)".
- The variables "`g_SIG…_flag`" should [use the data type "`sig_atomic_t`"](https://www.securecoding.cert.org/confluence/display/c/SIG31-C.+Do+not+access+shared+objects+in+signal+handlers).
- The function "[InfoLog](https://github.com/calvinwilliams/hetao/blob/029690fe2638a7568483ea3c9f768dd1c1b7b845/src/LOGC.h#L225)" does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers).

**Comment by calvinwilliams** [comment]
Thanks , I will fix it two days later

**Comment by elfring** [comment]
Would it be better to keep this issue open until it will be really fixed anyhow?

**Comment by calvinwilliams** [comment]
Thank you for your advice , I fixed it ^_____________________^

**Comment by elfring** [comment]
How do you think about to refer to the corresponding commit directly?
