### ISSUE TITLE
Windows 上无法启动

### ISSUE THREAD

**Issue by mengmo** [calvinwilliams/hetao#6]
`“D:\localhost\hetao\bin\hetao.exe”的激活上下文生成失败。 找不到从属程序集 Microsoft.VC90.DebugCRT,processorArchitecture="x86",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.21022.8"。 请使用 sxstrace.exe 进行详细诊断。`

`“D:\localhost\hetao\bin\hetaocheck.exe”的激活上下文生成失败。 找不到从属程序集 Microsoft.VC90.DebugCRT,processorArchitecture="x86",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.21022.8"。 请使用 sxstrace.exe 进行详细诊断。`

不支持安装到其他路径还是对 VCRedist 的 version 有要求？

**Comment by calvinwilliams** [comment]
我对VC9.0不太熟，你把安装路径设置到 C:\Program Files\hetao试试

**Comment by mengmo** [comment]
应该跟安装路径关系不大
这次在一台 Windows 7 的 PC 上，放哪儿都行
上次是在 Windows 10 的 PC 上，但是以前为了测试，我将 vcredist 从2005到2017无论 x64还是 x86全都装上了

**Comment by calvinwilliams** [comment]
^_^
